#!/usr/bin/env bash
#
# Searches a git repository for API keys.

readonly VERSION=$(cat VERSION)
USAGE='[--help | -h] [--version | -V]'
SUBDIRECTORY_OK=Yes
NONGIT_OK=No
. "$(git --exec-path)/git-sh-setup"   # see git-sh-setup(1)

readonly ERR_GETOPT=1
readonly ERR_OPTIONS=2

main() {
    local pathspecs="$@"
    grep -vE -e '^[[:space:]]*#' regexps | git grep -E -f - -- "$pathspecs"
}

readonly SHORT_OPT_STR='hV'
readonly LONG_OPT_STR='help,version'
TEMP=$(getopt -o $SHORT_OPT_STR -l $LONG_OPT_STR -n 'git-key-grep' -- "$@")
if [[ $? -ne 0 ]]; then
    exit $ERR_OPTIONS
fi
eval set -- "$TEMP"
unset TEMP

while true; do
    case "$1" in
        '-h'|'--help')
            usage
            exit 0
            ;;
        '-V'|'--version')
            echo "git key-grep v$VERSION"
            exit 0
            ;;
        '--')
            shift
            break
            ;;
        *)
            echo "$0 internal error!" >&2
            exit $ERR_GETOPT
            ;;
    esac
done

echo 'Remaining arguments:'
for arg; do
    echo "--> '$arg'"
done

main "$@"
